on:
  workflow_call:
    inputs:
      MAIN_ACCESS_KEY:
        required: true
        type: string
      ALT_ACCESS_KEY:
        required: true
        type: string
    secrets:
      MAIN_SECRET_KEY:
        required: true
      ALT_SECRET_KEY:
        required: true

jobs:
  s3_tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          repository: rabataio/s3-ceph-tests
          ref: feature/TRCS-107

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install tox

      - name: Update config file
        run: |
          sed -i "s|<main_access_key>|${{ inputs.MAIN_ACCESS_KEY }}|" s3tests.conf
          sed -i "s|<main_secret_key>|${{ secrets.MAIN_SECRET_KEY }}|" s3tests.conf
          sed -i "s|<alt_access_key>|${{ inputs.ALT_ACCESS_KEY }}|" s3tests.conf
          sed -i "s|<alt_secret_key>|${{ secrets.ALT_SECRET_KEY }}|" s3tests.conf

      - name: Test
        env:
          S3TEST_CONF: s3tests.conf
          S3_USE_SIGV4: true
        run: tox
