name: CEPH S3 Tests

on:
  pull_request:
    branches:
      - master

jobs:
  s3_test:
    uses: rabataio/s3-ceph-tests/.github/workflows/reusable_s3_tests.yml@feature/TRCS-107
    with:
      MAIN_ACCESS_KEY: ${{ vars.MAIN_ACCESS_KEY }}
      ALT_ACCESS_KEY: ${{ vars.ALT_ACCESS_KEY }}
    secrets:
      MAIN_SECRET_KEY: ${{ secrets.MAIN_SECRET_KEY }}
      ALT_SECRET_KEY: ${{ secrets.ALT_SECRET_KEY }}
