name: Ceph S3 Tests

on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 10 * * *'

jobs:
  s3_test:
    uses: ./.github/workflows/s3_tests_manual.yml
    with:
      environment: RCS stage
    secrets:
      MAIN_SECRET_KEY: ${{ secrets.MAIN_SECRET_KEY }}
      ALT_SECRET_KEY: ${{ secrets.ALT_SECRET_KEY }}
