name: Ceph S3 Tests

on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 10 * * *'

jobs:
  s3_test:
    uses: ./.github/workflows/s3_tests_reusable.yml
    with:
      HOST: ${{ vars.HOST }}
      MAIN_ACCESS_KEY: ${{ vars.MAIN_ACCESS_KEY }}
      ALT_ACCESS_KEY: ${{ vars.ALT_ACCESS_KEY }}
    secrets:
      MAIN_SECRET_KEY: ${{ secrets.MAIN_SECRET_KEY }}
      ALT_SECRET_KEY: ${{ secrets.ALT_SECRET_KEY }}
